#!/bin/bash
PREFIX=`brew --prefix 2> /dev/null`
REPO=`brew --repository 2> /dev/null`

if [ -f $PREFIX/etc/bash_completion.d/git-completion.bash ]; then
  . $PREFIX/etc/bash_completion.d/git-completion.bash
fi

if [ -f $REPO/Library/Contributions/brew_bash_completion.sh ]; then
  . $REPO/Library/Contributions/brew_bash_completion.sh
fi

if [ -x "`which command_completion_for_rake`" ]; then
    complete -C "`which command_completion_for_rake`" -o default rake
fi

if [ -x "`which complete_bundle_bash_command`" ]; then
  eval `complete_bundle_bash_command init`
fi

_play() {
    local cur=${COMP_WORDS[COMP_CWORD]}
    COMPREPLY=( $(compgen -f -X '!*.@(avi|mkv|mp4|ogg|flv)' -- "$cur") $( compgen -d -- "$cur" ) )
    return 0
}

alias play=open

complete -o filenames -F _play play
