#!/usr/bin/ruby
require 'irb/completion'
begin
  require 'irb/ext/save-history'
rescue LoadError # 3.3+
end

IRB.conf[:SAVE_HISTORY] = 1000
IRB.conf[:HISTORY_FILE] = "#{ENV['HOME']}/.irb_history"
IRB.conf[:PROMPT_MODE] = :SIMPLE
IRB.conf[:AUTO_INDENT] = true
